title: Bernardin LIGAN
logo: /assets/img/ligan.jpg
description: I am proficient in computer vision, Times series, and MLOps. I have a love for AI-based solutions that support the Sustainable Development Goals (SDGs)
#show_downloads: true
<h3 align="left">Connect with me:</h3>
<p align="left">
<a href="https://twitter.com/bernardinligan" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/twitter.svg" alt="bernardinligan" height="30" width="40" /></a>
<a href="https://linkedin.com/in/bernardin-ligan" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/linked-in-alt.svg" alt="bernardin-ligan" height="30" width="40" /></a>
<a href="https://kaggle.com/bernardin ligan" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/kaggle.svg" alt="bernardin ligan" height="30" width="40" /></a>
</p>
remote_theme: pages-themes/minimal@v0.2.0
