title: Bernardin LIGAN
# logo: /assets/img/ligan.jpg
#description: I  am a data scientist driven by a commitment to creating value. My passion lies in leveraging data and artificial intelligence to address challenges associated with sustainable development.

#show_downloads: true

remote_theme: pages-themes/minimal@v0.2.0
